version: "3.8"

services:
  watsonx:
    build:
      context: .
      dockerfile: Dockerfile
    image: watsonx-code-assistant
    container_name: watsonx-code-assistant
    ports:
      - "5000:5000"
      - "11434:11434"
    volumes:
      - watsonx_models:/data/models
      - watsonx_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PORT=5000
      - OLLAMA_HOST=localhost
      - OLLAMA_PORT=11434
      - MODEL_CACHE_DIR=/data/models
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - watsonx
    restart: unless-stopped

volumes:
  watsonx_models:
  watsonx_data:
