apiVersion: apps/v1
kind: Deployment
metadata:
  name: watsonx-code-assistant
  namespace: {{NAMESPACE}}
  labels:
    app: watsonx-code-assistant
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watsonx-code-assistant
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: watsonx-code-assistant
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        gpu: "true"
      containers:
      - name: watsonx-code-assistant
        image: {{IMAGE}}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10000
          runAsGroup: 10001
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: "6"
            memory: "12Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: "8Gi"
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 11434
          name: ollama
        env:
        - name: PORT
          value: "5000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "production"
        - name: OLLAMA_HOST
          value: "localhost"
        - name: OLLAMA_PORT
          value: "11434"
        - name: MODEL_CACHE_DIR
          value: "/data/models"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: watsonx-config
              key: TZ
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: TF_GPU_ALLOCATOR
          value: "cuda_malloc_async"
        - name: TF_XLA_FLAGS
          value: "--tf_xla_auto_jit=2"
        envFrom:
        - secretRef:
            name: watsonx-secrets
        volumeMounts:
        - name: model-storage
          mountPath: /data/models
          readOnly: false
        - name: app-data
          mountPath: /app/data
          readOnly: false
        - name: tmp-dir
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 30
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: watsonx-models-pvc
      - name: app-data
        persistentVolumeClaim:
          claimName: watsonx-data-pvc
      - name: tmp-dir
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      serviceAccountName: watsonx-sa
      terminationGracePeriodSeconds: 60
